services:
  db: 
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # equivalent to True
    volumes:
      - "./backend/db:/docker-entrypoint-initdb.d" # this is how we persist a sql db even when container stops
      - "./backend/dump:/var/lib/mysql"
  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - "./backend/website:/var/www/html" # sync the current dir on local machine to the dir of container
    ports:
      - 80:80
      - 443:443 # for future ssl traffic
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    links:
      - db
  frontend:
    build:
      dockerfile: ./angular/Dockerfile
    ports:
      - 4200:4200
    volumes:
      - "./app/node_modules"
      - "./angular:/app"

volumes:
  dump: